# Generated by Django 3.2.8 on 2022-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20220128_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facescan',
            name='image',
            field=models.ImageField(default='0', upload_to='images'),
        ),
    ]
