# Generated by Django 3.2.8 on 2022-01-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_facescan_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facescan',
        ),
    ]
