# Generated by Django 4.0.1 on 2022-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_delete_facescan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facescan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
    ]
