# Generated by Django 3.2.11 on 2022-02-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_facescan_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facescan',
            name='uploadedimage',
        ),
    ]
