# Generated by Django 3.2.11 on 2022-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_alter_facescan_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facescan',
            name='uploadedimage',
        ),
        migrations.RemoveField(
            model_name='facescan',
            name='username',
        ),
        migrations.AddField(
            model_name='facescan',
            name='file',
            field=models.FileField(default=False, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='facescan',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
