# Generated by Django 3.2.11 on 2022-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_auto_20220205_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facescan',
            name='file',
        ),
        migrations.RemoveField(
            model_name='facescan',
            name='image',
        ),
        migrations.AddField(
            model_name='facescan',
            name='avatar',
            field=models.ImageField(default=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='facescan',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
