# Generated by Django 3.2.11 on 2022-02-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_auto_20220205_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facescan',
            old_name='name',
            new_name='username',
        ),
    ]
