# Generated by Django 3.2.11 on 2022-02-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_rename_name_facescan_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facescan',
            old_name='avatar',
            new_name='image',
        ),
    ]
