# Generated by Django 4.0.2 on 2022-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0022_alter_forgot_mailbox_alter_forgot_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facescan',
            name='mailbox',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
